### ISSUE TITLE
Bug: Royal Scribe saved notation value not being used

### ISSUE THREAD

**Issue by sthgrau** [dox4242/RG-tools#18]
In line 172 of rs/index.js, the code is trying to get the notation from the options.save.not field, but that does not exist. The current name appears to be options.save.tab.

The following works in my local copy:

`notation: this.save.options.not != null ? this.save.options.not : this.save.options.tab != null ? this.save.options.tab : (this.save.options.notation ? 1 : 0),`

**Comment by nyanlathotep** [comment]
Since the editor is something of a read/write version of scribe and scribe uses the old codec, scribe's been deprecated and won't be supported anymore.
