### ISSUE TITLE
Scribe-like rendering on the editor

### ISSUE THREAD

**Issue by nyanlathotep** [dox4242/RG-tools#19]
Since scribe's been deprecated in favor of the editor, the editor rendering values in a more readable format might be a good thing to add, especially for times. For consistency, it'll also need to accept values in those formats.

**Comment by dox4242** [comment]
Seems like it might be possible to put a toggle switch near the top to disable editing...I'm not good at that kind of Vue shenanigans, but if it means updating all the widgets, I'm game for that task.

**Comment by nyanlathotep** [comment]
I'm not sure disabling editing is really necessary, it's not exactly easy to edit by accident, and even if you do, you can just re-enter save to revert changes, but I'll create a separate issue for that. This is definitely gonna require some widget work, probably the best approach is a widget consisting of a text field with getters and setters that can render input to a particular format and accept input in a variety of appropriate formats, something along those lines. Might also want, say, an option to pass to stat widgets to specify that something is a time, and have it create the appropriate edit widgets inside itself.

**Comment by dox4242** [comment]
So for the text field rendering input, I'm picturing the widget looking up the value of some data field, doing some processing to the value, and displaying a formatted value. But I'm not sure how that would work with users entering some input value. Will the widget take, say "3600" (seconds) and then replace it with "1 hour" or "1h", or will a user enter any of those three strings and the widget will be able to parse them all into the appropriate value (whether seconds or ticks, or whatnot)?

**Comment by dox4242** [comment]
Secondly, widgets creating widgets inside themselves??  o_Õ

**Comment by nyanlathotep** [comment]
Yeah, the getter should take 3600 and display "1h", and the setter should take 3600 or "1h" or perhaps "1:00:00", whatever formats it should take, and convert them back to 3600 for the model. And widgets can create other widgets inside themselves just like other elements.

**Comment by dox4242** [comment]
Okay, should the setters only take one format, then?

**Comment by nyanlathotep** [comment]
Everything should still take plain numbers, but times should take at least times like 1h 36m and such. A good regex for that is probably something like `(\d+[DHMSdhms]\s*)+`. It might be reasonable to take colon delimited times as well, `(\d+:?)+` should do that. Numbers might want to support short scale rendering and input, in addition to plain numbers (which already handles scientific). Like scribe, it would be possible to set the number rendering format based on the save's options. But times are definitely the more important of the two.
