### ISSUE TITLE
trophy series widgets broken

### ISSUE THREAD

**Issue by nyanlathotep** [dox4242/RG-tools#24]
trophy series widgets are alternating between giving the last trophy and removing all trophies, regardless of what is chosen

**Comment by dox4242** [comment]
I sketched up some notes for fixing this bug, but I haven't gotten a working implementation yet:

for each trophy in series, 
- if trophy in save data,
- - if trophy selected: add it
- - else: remove it

compressed trophy series in save data:
46, coin gain
47, click coin gain
41, treasure clicks
112, mana
40, spells
45, faction coins
51, assistants
170, artifacts
49, gems
162, rubies
55, upgrades
50, reincarnations
17, total buildings
23, farms
27, inns
16, blacksmiths
37, warrior barracks
35, slave pens
29, knights jousts
33, orcish arenas
39, wizard towers
38, witch conclaves
18, cathedrals
20, dark temples
19, citadels
32, necropolises
34, royal castles
22, evil fortresses
25, heaven's gates
26, hell portals
21, deep mine
36, stone pillar
14, alchemist labs
31, monasteries
30, labyrinths
28, iron strongholds
15, ancient pyramids
24, halls of legends
