### ISSUE TITLE
Save Codec broken with beta saves

### ISSUE THREAD

**Issue by nyanlathotep** [dox4242/RG-tools#32]

**Comment by dox4242** [comment]
You'll have to share the beta code with me before I can update the save codec for the new fields, since I'm not a beta tester.

**Comment by nyanlathotep** [comment]
Latest dump is https://cdn.discordapp.com/attachments/307247596383240202/313353966190854150/beta-2.7.0.13.zip

**Comment by dox4242** [comment]
Well, I gave it a shot, but I can't test it. Let me know how it works for you.
