### ISSUE TITLE
Enchancement: Add clear reaserch button/link

### ISSUE THREAD

**Issue by sthgrau** [dox4242/RG-tools#34]
Sometimes you just need to start from nothing with research, it would be nice if there were a link to clear all checkboxes for current research.

**Comment by sthgrau** [comment]
Fwiw, I gave it a hack and slash attempt, but it doesn't appear to be dependent on the actual checkbox state somehow.

**Comment by dox4242** [comment]
That would've been a handy feature while I was testing....It would still be a handy feature....

**Comment by dox4242** [comment]
Fixed. Added "all" checkboxes for unlocking and owning the researches
