### ISSUE TITLE
exported save is corrupted

### ISSUE THREAD

**Issue by czras** [dox4242/RG-tools#36]
When I load a v2.7.2.0 save and generate a save witout changing anything, the generated output save is not identical to the input one. Also I can not load the generated save as input. Seeing this on the console on load:

DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at Object.decodeBytes (http://dox4242.github.io/lib/savecodec2.js:119:12)
    at Object.Decode (http://dox4242.github.io/lib/savecodec2.js:20:36)
    at controller.loadSave (http://dox4242.github.io/edit/edit.js:106:33)
    at http://dox4242.github.io/edit/edit.js:1347:22

**Comment by dox4242** [comment]
That's a bad sign and, unfortunately, I wasn't able to replicate the error; would you mind putting a copy of the save string that causes this error on pastebin or elsewhere so I could experiment with it?

**Comment by helpiminabox** [comment]
I too have this issue (though on 2.7.2.3), here is what I input: 
https://hastebin.com/raw/vumivakufe
Without changing anything and generating a save I get:
https://hastebin.com/raw/yehawucuri

Edit: Looking in the console I get a different error: 

Uncaught TypeError: Cannot read property 'u1' of undefined
    at Di.checkLSavail (edit.js:1253)
    at Di.checkLSavail (vue.min.js:6)
    at controller.loadSave (edit.js:119)
    at edit.js:1347

**Comment by lukeparaventi** [comment]
I had the same issue using Chrome. Switched to Edge and was able to edit and import without issue.

**Comment by helpiminabox** [comment]
Can confirm that edited saves are accepted by the game when using Edge at least.

**Comment by necrodoom** [comment]
This is a mis-mash of different issues all in one page, the original error 'Failed to execute 'atob' on 'Window'' is something we havent been able to replicate, the second error 'Cannot read property 'u1' of undefined' we replicated successfully and should be easy enough to fix, and the import issue which is a browser related issue when clicking 'copy save' due to the browser "helpfully" cutting down the save string to fit.

**Comment by czras** [comment]
Sorry guys I was busy levelling... I am using Chrome on Linux, so there might be the problem. I will try it out on FF.

**Comment by dox4242** [comment]
Closing vague issue thread. Please open a new issue if your error persists.
