### ISSUE TITLE
LC: doesn't show excavation, even though RG shows a 1 bubble

### ISSUE THREAD

**Issue by jnahmias** [dox4242/RG-tools#40]
So, I'm in Realm Grinder and have made it to R21.  The Excavation tab shows 1 artifact available, but Lara Crypt doesn't know anything about it.
[R21_sav.txt](https://github.com/dox4242/dox4242.github.io/files/1439685/R21_sav.txt)

**Comment by jnahmias** [comment]
FYI, it's the ancient cocoa bean artifact

**Comment by nyanlathotep** [comment]
Yeah, LC doesn't yet have artifact specs for the newer artifacts.

**Comment by dox4242** [comment]
Added the thing.
