### ISSUE TITLE
RWS : improve readability of DB forecasts

### ISSUE THREAD

**Issue by sholan** [dox4242/RG-tools#41]
Hello,
A quite simple suggestion, to debate :

- [ ] Use abreviations for effects (keep font color)
- [ ] Create a [key](http://www.wordreference.com/definition/key#advanced_8) for these abreviations (I don't know if this term will be understood at first sight, added a link to a dictionnary for the meaning I mean)
- [ ] Align every effect to a grid (all "blues" will be aligned)
- [ ] Find an idead to make it work with DB6 and DB7 (I can't find it ATM)

Of course, this task list is a suggestion.

**Comment by necrodoom** [comment]
Resolved
