### ISSUE TITLE
Save Editor Suggestion

### ISSUE THREAD

**Issue by MithicSpirit** [dox4242/RG-tools#42]
I think it would be interesting to edit whether you have the Blessing of Heroes/Kings/Gods or not in the save editor, unless if that's illegal or something...

**Comment by nyanlathotep** [comment]
It's not illegal to alter data on a computer you own, at least not without some very disturbing laws. The trouble here is that the gifts are decided remotely, by kong or perhaps by something else on mobile platforms, I don't know well how the microtransactions on mobile work. The gifts are the only thing not decided directly or indirectly by the save.

It might be possible to do this with an http proxy, but I think kong's responses are signed, which'd prevent you from forging them, and in any case, this is beyond the scope of these tools.
