### ISSUE TITLE
Veteran Figurine can't be obtained in A2

### ISSUE THREAD

**Issue by Brilliand** [dox4242/RG-tools#49]
I was playing with the save editor, and I noticed that Lara Crypt incorrectly includes the Veteran Figurine as an eligible artifact past R100 if it hasn't already been obtained by then.  This throws off the preditions for other artifacts.

**Comment by Brilliand** [comment]
I see that g00f's site lists the requirement for the veteran figurine as simply "R90+".  There must be another requirement that's been missed, because when I edit a save without the Veteran to R159, the game (usually) shows too few eligible artifacts to be including the Veteran among them, and Lara Crypt's predictions are wrong unless I feed it an edited version of the save that has the Veteran added.

**Comment by Brilliand** [comment]
I edited in merc research, and the game is now showing a number of eligible artifacts that matches Lara Crypt, so it looks like merc research is the hidden requirement.

**Comment by dox4242** [comment]
I'm not sure what the exact problem is. My attempt to replicate it involved removing Veteran Figurine from my save file (on R114). I used Lara Crypt, and both Veteran Figurine and Nightmare Figment popped up as expected. I checked the source code and there were no references to the upgrade for Merc research in the Veteran Figurine unlock code.

**Comment by Brilliand** [comment]
I've finding it hard to recreate the problem too, but I do have this save that exhibits the problem:

https://pastebin.com/xBPqKj99

R114, doesn't have the Veteran Figurine, but the game says no artifacts available.

And... apparently no matter what I edit back in, the game won't allow that save to excavate the Veteran Figurine.  I even tried editing it back to R98 and playing as mercs for a bit.  (This save originated as a personal challenge to jump straight to R159 from a hard reset and see how much I could unlock.)

**Comment by necrodoom** [comment]
So i went back to this issue, the hidden req appears to be a requirement for all challenges to be completed. Im not exactly sure how to went though all of A1 without all challenges, however.

**Comment by necrodoom** [comment]
fixed at some point
