### ISSUE TITLE
New update?

### ISSUE THREAD

**Issue by AlexSargon** [dox4242/RG-tools#51]
I've been using the Save Editor for some time, and it has really been a great help. I only use it sparingly, when I hit a wall or just don't want to grind 100+ hours of spell activity time to unlock something.

3.3.0.0 just dropped, and I kinda wanted to get around all of the hours of spell casting needed to successfully excavate the new Oil Lamp artifact. 100+ days of casting time for Fairy Chanting, Hellfire Blast, *and* Brainwave??? Even if it was 100+ days TOTAL, that would be ridiculous.

Problem is, I can't import any saves. Even the smallest change makes an import fail. I've made sure I had the whole string of text before copying. It reads my exported strings perfectly, from what I can tell, but importing doesn't work. :(

Will there be an update, or is this project pretty much a finished product?

**Comment by michaelts1** [comment]
About the new artifacts, they are very easy to get. I got them without any effort.
Go chaos, excavate (until you get it). Go balance, excavate. Go order, excavate. Simple.
As for the editor, I really hope that it will be updated.

**Comment by AlexSargon** [comment]
Thanks. Yeah, I had already gotten the last two artifacts without trying very hard. Was actually surprised when I got the Oil Lamp. Apparently, it was 100d combined casting across the 3 spells, not 100d each.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by michaelts1** [comment]
yay! the editor is now updated!

**Comment by AlexSargon** [comment]
Most excellent! Thanks for letting me know. Cheers!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
